tcp:

  routers:

    user0001-01:                    #  User 0001, Coordinator 01 (attached to zigbee2mqtt-01)
      entryPoints:
        - z2m-01                    # Matches on TCP port 6001 (see docker-compose.yml)
      rule: HostSNI(`*`)
      service: user0001-01-svc

    user0002-01:                    #  User 0002, Coordinator 01 (attached to zigbee2mqtt-02)
      entryPoints:
        - z2m-02                    # Matches on TCP port 6002 (see docker-compose.yml)
      rule: HostSNI(`*`)
      service: user0002-01-svc


  services:

    user0001-01-svc:                    #  User 0001, Coordinator 01 (attached to zigbee2mqtt-01)
      loadBalancer:
        servers:
          - address: "100.64.0.2:6638"  # Coordinator 01 (TCP port 6638)

    user0002-01-svc:                    #  User 0002, Coordinator 01 (attached to zigbee2mqtt-02)
      loadBalancer:
        servers:
          - address: "100.64.0.3:6638"  # Coordinator 01 (TCP port 6638)      
          